my:
  server:
    #addr: 106.75.107.221
    addr: 192.168.137.150
spring:
  datasource:
    url: jdbc:mysql://${my.server.addr}:3306/mall_ums?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: tarena2017Up;
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    default-property-inclusion: always
  application:
    name: mall-ums
  cloud:
    nacos:
      discovery:
        server-addr: ${my.server.addr}:8848
  redis:
    host: ${my.server.addr}
    port: 6379
    password:
dubbo:
  application:
    name: mall-ums
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://${my.server.addr}:8848
    use-as-metadata-center: false
    use-as-config-center: false
  consumer:
    check: false
  cloud:
    subscribed-services:
logging:
  level:
    cn.tedu.mall: trace