my:
  server:
    addr: localhost
spring:
  datasource:
    url: jdbc:mysql://${my.server.addr}:3306/mall_seckill?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: always
  application:
    name: mall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: ${my.server.addr}:8848
    sentinel:
      transport:
        port: 8870
        dashboard: 127.0.0.1:8080
  redis:
    host: ${my.server.addr}
    port: 6379
    password:
  rabbitmq:
    host: ${my.server.addr}
    port: 5672
    username: user
    password: 123456
    virtual-host: /

dubbo:
  application:
    name: mall-seckill
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://${my.server.addr}:8848
    use-as-metadata-center: false
    use-as-config-center: false
  consumer:
    check: false
logging:
  level:
    cn.tedu.mall: trace