my:
  server:
    addr: localhost
  level:
    cn.tedu.mall: trace
spring:
  datasource:
    url: jdbc:mysql://${my.server.addr}:3306/mall_oms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mall-order
  jackson:
    # 为null的属性不显示到响应结果中
    default-property-inclusion: always
  cloud:
    nacos:
      discovery:
        server-addr: ${my.server.addr}:8848
  redis:
    port: 6379
    host: ${my.server.addr}
    password:
dubbo:
  application:
    name: mall-order
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://${my.server.addr}:8848
    use-as-config-center: false
    use-as-metadata-center: false
  consumer:
    check: false
#seata服务端
seata:
  tx-service-group: csmall_group
  service:
    vgroup-mapping:
      csmall_group: default
    grouplist:
      default: ${my.server.addr}:8091
  client:
    undo:
      log-serialization: kryo