my:
  server:
    #addr: 192.168.137.150
    addr: 106.75.107.221
spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    admin:
      jdbc-url: jdbc:mysql://${my.server.addr}:3306/mall_ams?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: tarena2017Up;
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
    user:
      jdbc-url: jdbc:mysql://${my.server.addr}:3306/mall_ums?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: tarena2017Up;
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  redis:
    host: ${my.server.addr}
    port: 6379
    password:
logging:
  level:
    cn.tedu.mall: info
