my:
  server:
    addr: localhost
spring:
  application:
    name: mall-search
  jackson:
    default-property-inclusion: always
  cloud:
    nacos:
      discovery:
        server-addr: http://${my.server.addr}:8848
  elasticsearch:
    rest:
      uris: http://${my.server.addr}:9200
  redis:
    host: ${my.server.addr}
    port: 6379
    password:
      #dubbo
dubbo:
  application:
    name: mall-search
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://${my.server.addr}:8848
    use-as-config-center: false
    use-as-metadata-center: false
  consumer:
    check: false
logging:
  level:
    cn.tedu.mall: trace