my:
  server:
    addr: localhost
# 日志显示级别
logging:
  level:
    cn.tedu.mall: trace
spring:
  application:
    name: mall-front
  jackson:
    default-property-inclusion: always
  cloud:
    nacos:
      discovery:
        server-addr: ${my.server.addr}:8848
  redis:
    host: ${my.server.addr}
    port: 6379

dubbo:
  application:
    name: mall-front
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://${my.server.addr}:8848
    use-as-config-center: false
    use-as-metadata-center: false
  consumer:
    check: false
  cloud:
    subscribed-services: mall-product