logging:
  level:
    cn.tedu.mall: trace
server:
  port: 10003
  # 编码
  servlet:
    encoding:
      force: true
      charset: UTF-8
# Spring相关配置
spring:
  # 控制器配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # 激活的profile配置
  profiles:
    active: test

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  secret: mySecret
  # JWT的超期限时间(60*60*24)
  expiration: 604800
  tokenHead: Bearer
knife4j:
  # 开启增强配置
  enable: true
  # 生产环境屏蔽，开启将禁止访问在线API文档
  production: false
  # Basic认证功能，即是否需要通过用户名、密码验证后才可以访问在线API文档
  basic:
    # 是否开启Basic认证
    enable: false
    # 用户名，如果开启Basic认证却未配置用户名与密码，默认是：admin/123321
    username: root
    # 密码
    password: root
